# Generated by Django 3.2.9 on 2021-12-15 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('_title', models.CharField(default='Untitled', max_length=120, verbose_name='Title')),
                ('_desciption', models.TextField(verbose_name='Description')),
                ('_created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
