# Generated by Django 3.2.9 on 2021-12-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='_desciption',
            new_name='_description',
        ),
    ]
