# Generated by Django 3.2.9 on 2021-12-16 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_rename__desciption_diaryentry__description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
