# Generated by Django 4.0.2 on 2022-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_diaryentry__created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='_audioLink',
            field=models.TextField(blank=True, verbose_name='audioFileLink'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='_imageLinks',
            field=models.JSONField(blank=True, default='', verbose_name='imageFileLinks'),
            preserve_default=False,
        ),
    ]
