# Generated by Django 4.0.2 on 2022-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diaryentry__audiolink_diaryentry__imagelinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='_imageLinks',
            field=models.JSONField(blank=True, null=True, verbose_name='imageFileLinks'),
        ),
    ]
