# Generated by Django 4.0.7 on 2022-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_diaryentry__audiolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='_is_private',
            field=models.BooleanField(default=False),
        ),
    ]
