# Generated by Django 4.0.7 on 2022-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_diaryentry__is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='_is_private',
            field=models.BooleanField(default=True),
        ),
    ]
