# Generated by Django 3.2.9 on 2022-01-01 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo__user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='_created_on',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
