# Generated by Django 3.2.9 on 2022-01-03 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo__created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='_created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
