# Generated by Django 4.0.8 on 2022-12-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo__created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='_is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
