// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91ItGd0HT83Q38I8AWi-OwlK9l_gP17I',
    appId: '1:965674940805:web:aa9139f61379ba3cad2cec',
    messagingSenderId: '965674940805',
    projectId: 'thelyfapp-971b5',
    authDomain: 'thelyfapp-971b5.firebaseapp.com',
    storageBucket: 'thelyfapp-971b5.appspot.com',
    measurementId: 'G-MTPXNGX7EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohfzgOQgqOG5e-vDCL7c7uqIaeUD3Qto',
    appId: '1:965674940805:android:2254dfa91eae4b0aad2cec',
    messagingSenderId: '965674940805',
    projectId: 'thelyfapp-971b5',
    storageBucket: 'thelyfapp-971b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnwQfH3x8E9Q2kqcyWLPIpYRYKqkqDiyE',
    appId: '1:965674940805:ios:c9572944d141d8aaad2cec',
    messagingSenderId: '965674940805',
    projectId: 'thelyfapp-971b5',
    storageBucket: 'thelyfapp-971b5.appspot.com',
    iosBundleId: 'com.inCognoSLabs.lyf',
  );
}
