# Generated by Django 3.2.9 on 2021-12-21 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfuser',
            name='_start_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
