# Generated by Django 3.2.9 on 2022-01-01 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_lyfuser__start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfuser',
            name='_start_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
