# Generated by Django 4.0.7 on 2022-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_lyfuser__start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
